### ISSUE TITLE
iphone

### ISSUE THREAD

**Issue by alfu32** [SketchUp/ruby-api-docs#19]
if this is the source for http://ruby.sketchup.com/ 

screen does not scroll on iphone.
it is completely unusable on an iphone.
tried in safari and chrome.

**Comment by thomthom** [comment]
Yes, we have an internal issue logged for this. The stylesheet activated for small monitors is currently bugged.

This is the repo for the generated source. The actual YARD template that generates it is located in another repo: https://github.com/SketchUp/sketchup-yard-template

**Comment by alfu32** [comment]
quick fix

in style.css
line 57
```css
@media (max-width: 920px) {
  .nav_wrap { display: none; }
}
```
modify
```css
@media (max-width: 920px) {
  .nav_wrap { display: none; }
  #main { 
    /*height: 100%; not necessary for this test but present in the  @media (min-width: 920px) */
    /* overflow: auto; not necessary for this test but present in the  @media (min-width: 920px) */
    /* at least this */
    overflow-y: scroll;
  }
}
```
just copy the rule
 ```css
#main { height: 100%; overflow: auto; }
```
from line 64 inside 
```css
@media (max-width: 920px) {
```
_tested in chrome, dev tools open , activate responsive desgn, resize device width to less than 920px,or select iphone6_
before : no body scrolling, no menu-icon in view, if menu open, menu scrolls
after : body scrolls , menu icon in view, menu scrolls;
